apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: {{ include "testing-automation.fullname" . }}
spec:
  type: 0
  resourceID: {{ .Values.armAuth.identityResourceID }}
  clientID: {{ .Values.armAuth.identityClientID }}
