apiVersion: batch/v1beta1
kind: CronJob
metadata:
  # name: {{ include "testing-automation.fullname" . }}-[replace this by the name of the cronjob]
  labels:
    {{- include "testing-automation.labels" . | nindent 4 }}
    # app: testing-automation-[replace this by the name of the cronjob]
spec:
  # schedule: "{{ .Values.[replace this by the chronschedule env name set in the values] }}"
  startingDeadlineSeconds: 100
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            aadpodidbinding: {{ include "testing-automation.fullname" . }}

        spec:
          restartPolicy: Never
          nodeSelector:
            kubernetes.io/os: linux
          containers:
          - # name: {{ include "testing-automation.fullname" . }}-[replace this by the name of the cronjob]                  
            image: {{ .Values.image.repository }}:{{ .Values.appVersion | default .Chart.AppVersion }}
#             env: [set environment variables here based on the variables set in the values or it can be hardcoded]
#             - name: STEPS_TIMEOUT
#               value: "125000"
#             - name: TEST_TO_RUN
#               value: st00chrome
#             - name: TEST_USER
#               value: "{{ .Values.testUser }}"
#             - name: TEST_LOCAL_USER
#               value: "{{ .Values.testLocalUseridh2 }}"
#             - name: SPLUNK_INDEX
#               value: "{{ .Values.splunkIndex }}"
# {{- if .Values.keyVault.enabled }}              
#             - name: TEST_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: my-rockwell-test-password
#                   key: password
#             - name: TEST_LOCAL_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: testing-automation-idh-loginsuite-password
#                   key: loginsuite-password
#             - name: SPLUNK_TOKEN
#               valueFrom:
#                 secretKeyRef:
#                   name: splunk-collector-token
#                   key: token
#             - name: CLIENT_SECRET
#               valueFrom:
#                 secretKeyRef:
#                   name: testing-automation-idh-crudsuite-client-secret
#                   key: crudsuite-client-secret
# {{- end }}              
#             - name: PORTAL_URL
#               value: "{{ .Values.portalUrl }}"
#             - name: PORTAL_URL_HOME
#               value: "{{ .Values.homeUrl }}"
#             - name: IS_URL
#               value: "{{ .Values.isUrl }}"
#             - name: API_URL
#               value: "{{ .Values.apiUrl }}"
#             - name: BLOB_CORE_URL
#               value: "{{ .Values.blobCoreUrl }}"
#             - name: SPLUNK_HOST
#               value: "{{ .Values.splunkHost }}"
#             - name: AUTH0_URL
#               value: "{{ .Values.auth0Url }}"
{{- if .Values.keyVault.enabled }}
            volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
{{- end }}
          imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}
{{- if .Values.keyVault.enabled }}
          volumes:
          - name: secrets-store-inline
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: {{ include "testing-automation.fullname" . }}
{{- end }}