{{- if .Values.keyVault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "testing-automation.fullname" . }}
spec:
  provider: azure
  secretObjects:  
  - data:
    - key: password
      objectName: my-rockwell-test-password
    secretName: my-rockwell-test-password
    type: Opaque
  - data:
    - key: loginsuite-password
      objectName: testing-automation-idh-loginsuite-password
    secretName: testing-automation-idh-loginsuite-password
    type: Opaque
  - data:
    - key: crudsuite-password
      objectName: testing-automation-idh-crudsuite-password
    secretName: testing-automation-idh-crudsuite-password
    type: Opaque
  - data:
    - key: crudsuite-client-secret
      objectName: testing-automation-idh-crudsuite-client-secret
    secretName: testing-automation-idh-crudsuite-client-secret
    type: Opaque
  - data:
    - key: crudsuite-stress-test-id
      objectName: testing-automation-idh-crudsuite-stress-test-id
    secretName: testing-automation-idh-crudsuite-stress-test-id
    type: Opaque
  - data:
    - key: token                                           # data field to populate
      objectName: splunk-collector-token                                  # name of the mounted content to sync. this could be the object name or the object alias
    secretName: splunk-collector-token                                       # name of the Kubernetes Secret object
    type: Opaque   
  - data:
    - key: perf-password
      objectName: testing-automation-perftest-password
    secretName: testing-automation-perftest-password
    type: Opaque                                                   # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls  

  parameters:
    usePodIdentity: "true"
    # useVMManagedIdentity: "true"
    #userAssignedIdentityID: "{{ .Values.keyVault.userAssignedId }}"
    keyvaultName: "{{ .Values.keyVault.name }}"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: my-rockwell-test-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: splunk-collector-token
          objectType: secret
        - |
          objectName: testing-automation-idh-loginsuite-password
          objectType: secret
        - |
          objectName: testing-automation-idh-crudsuite-password
          objectType: secret
        - |
          objectName: testing-automation-idh-crudsuite-client-secret
          objectType: secret
        - |
          objectName: testing-automation-idh-crudsuite-stress-test-id
          objectType: secret         
        - |
          objectName: testing-automation-perftest-password
          objectType: secret   
          
    resourceGroup: "{{ .Values.keyVault.resourceGroup }}"
    subscriptionId: "{{ .Values.keyVault.subscriptionId }}"
    tenantId: "{{ .Values.keyVault.tenantId }}"
{{- end }}
