name: Black Duck Scan Dispatch

on:
  push:
    branches:
      - release/**
      - hotfix/**
      - main
      - master
  workflow_dispatch:

env:
  BLACKDUCK_TIMEOUT: 360

jobs:
  blackduck-scan-dispatch:
    timeout-minutes: 8
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Get Last tag
        id: extract_last_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: unknown

      - name: Fire repository_dispatch for Black Duck Scanning
        # We don't want to wait, so we use a different action, which take different inputs.
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          repository: ${{ github.repository_owner }}/workflows
          token: ${{ secrets.READ_GITHUB_ACTIONS_PAT }}
          event-type: trigger-blackduck-scan
          client-payload: '{
                            "ref"               : "${{ github.ref }}",
                            "sha"               : "${{ github.sha }}",
                            "repo"              : "${{ github.repository }}",
                            "build_version"     : "${{ steps.extract_last_tag.outputs.tag }}"
                          }'
