name: Docker Build Common Services

on:
  workflow_dispatch:

env:
  DOCKER_FILE: "DockerfileCS"
  KUBERNETES_APP_NAME: "common-services-ta"

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetches entire history, so we can analyze commits since last tag.
          fetch-depth: 0
          token: ${{ secrets.READ_GITHUB_ACTIONS_PAT }}
          submodules: recursive
      - name: Docker Login to GitHub Container Registry
        run: |
          echo ${{ secrets.READ_WRITE_GITHUB_PACKAGES_PAT }} | docker login ${{ env.CONTAINER_REGISTRY_NAME }} --username ${{ secrets.READ_WRITE_GITHUB_PACKAGES_USER }} --password-stdin

      # Build the Docker image tagged for pre-release or release.
      - name: Build the Docker image
        run: |
          docker build . --file ${{ env.DOCKER_FILE }} --tag ${{ env.KUBERNETES_APP_NAME }}

      - name: Determine next tag
        id: next_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
          # RELEASE_BRANCHES: main
          PRERELEASE_SUFFIX: prerelease
          DRY_RUN: false

      - name: Re-tag and push the Docker image
        run: |
          docker tag ${{ env.KUBERNETES_APP_NAME }} ${KUBERNETES_APP_NAME}:${BUILD_VERSION}
          docker push ${KUBERNETES_APP_NAME}:${BUILD_VERSION}
        env:
          BUILD_VERSION: ${{ steps.next_tag.outputs.new_tag || 
                              steps.next_tag_dev.outputs.new_tag || 
                              github.event.inputs.tags }}